### DISCUSSION TITLE
single executable application is not working on windows

### DISCUSSION THREAD

**Discussion by yjl9903** [nodejs/single-executable#65] [Q&A] [answered]
Hello, I am trying building the example single executable application on windows, following this [document](https://nodejs.org/api/single-executable-applications.html). But the bundled binary is not working on Windows, and it does not output the `hello world` message and the sea warning message.

And I also tried directly running the copied node exectuable, and it also output nothing.

Reproduction: https://github.com/yjl9903/unbuild-sea/blob/main/.github/workflows/compile.yaml

Running logs: https://github.com/yjl9903/unbuild-sea/actions/runs/4752558049/jobs/8443057778

```yaml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.target }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: linux
            os: ubuntu-latest
            bin: hello
          - target: windows
            os: windows-latest
            bin: hello

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm

      - name: Install
        run: npm install
      
      - name: Copy on windows
        if: ${{ matrix.target == 'windows' }}
        run: |
          echo (Get-Command node).source 
          cp (Get-Command node).source ${{ matrix.bin }}
          echo '---'
          ls .
          echo '---'
          ls (Split-Path -Path (Get-Command node).source)
          echo '---'
          ./${{ matrix.bin }} --version
          echo '---'
      
      - name: Copy on linux
        if: ${{ matrix.target != 'windows' }}
        run: |
          cp $(command -v node) ${{ matrix.bin }} 

      - name: Build
        run: |
          node --experimental-sea-config sea-config.json
          npx postject ${{ matrix.bin }} NODE_SEA_BLOB sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2
          ./${{ matrix.bin }} world
      
      - name: Test on windows
        if: ${{ matrix.target == 'windows' }}
        run: |
          .\${{ matrix.bin }} world
      
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.bin }}-${{ matrix.target }}
          path: ./${{ matrix.bin }}
```
